name: Belt Test Build

on:
  push:
    branches:
    - main

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Restore NuGet packages
      run: dotnet restore
      working-directory: ./BeltTest

    - name: Run build
      shell: cmd 
      run: ./build.cmd

    - name: Save Package
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: ./BeltTest/BeltTestPackage/bin/**